version: "3.7"

services:

    nginx-webserver-termer:
        networks:
            default:
                aliases:
                    - termer

networks:
  default:
    external:
      name: parent-network